(define (read-file f)
  (with-input-from-file f
    (lambda ()
      (let loop ((lst '()))
        (let ((c (read-char)))
          (if (eof-object? c)
              (list->string (reverse lst))
              (loop (cons c lst))))))))

(define (split-string str c)
  (let ((len (string-length str)))
    (let loop ((lst '())
               (i 0)
               (b 0))
      (cond ((= i len)
             (if (= b i)
                 (reverse lst)
                 (reverse (cons (substring str b i) lst))))
            ((char=? (string-ref str i) c)
             (loop (cons (substring str b i) lst) (+ i 1) (+ i 1)))
            (else
             (loop lst (+ i 1) b))))))

(define (alphabetical-value word)
  (let ((sum 0))
    (do ((i 0 (+ i 1)))
        ((= i (string-length word)) sum)
      (set! sum (+ (- (char->integer (string-ref word i)) 64) sum)))))

(define (calculate-scores names)
  (let loop ((names names)
             (scores (list))
             (i 1))
    (if (null? names)
        (reverse scores)
        (loop (cdr names)
              (cons (* (alphabetical-value (car names)) i) scores)
              (+ i 1)))))

(define (main)
  (let* ((names (map (lambda (s) (substring s 1 (- (string-length s) 1)))
                     (split-string (read-file "0022_names.txt") #\,)))
         (names-sorted (sort string<? names))
         (scores (calculate-scores names-sorted))
         (sum (apply + scores)))
    (display sum)
    (newline)))

;; 871198282
(main)
