(define (divisors num)
  (let loop ((i 1)
             (lst '()))
    (if (> i (/ num 2))
        (reverse lst)
        (loop (+ i 1)
              (if (= (modulo num i) 0)
                  (cons i lst)
                  lst)))))

(define (sum-of-divisors num)
  (let loop ((i 1)
             (sum 0))
    (if (> i (/ num 2))
        sum
        (loop (+ i 1)
              (if (= (modulo num i) 0)
                  (+ sum i)
                  sum)))))

(define (abundant? num)
  (> (sum-of-divisors num) num))

(define (abundants min max)
  (let loop ((lst '())
             (i min))
    (if (> i max)
        (list->vector (reverse lst))
        (loop (if (abundant? i)
                  (cons i lst)
                  lst)
              (+ i 1)))))

(define (upper-bound vec num)
  (do ((first 0)
       (count (vector-length vec)))
      ((<= count 0) first)
    (let* ((step (quotient count 2))
           (i (+ first step)))
      (if (< (vector-ref vec i) num)
          (begin
            (set! first (+ i 1))
            (set! count (- count (+ step 1))))
          (set! count step)))))

(define (sum-of-two? vec num)
  (call-with-current-continuation
   (lambda (return)
     (let ((max (min (upper-bound vec num)
                     (- (vector-length vec) 1))))
       (do ((i 0 (+ i 1)))
           ((> i max) #f)
         (do ((j i (+ j 1)))
             ((> j max))
           (if (= (+ (vector-ref vec i)
                     (vector-ref vec j))
                  num)
               (return #t))))))))

(define (main)
  (let* ((N 28500)
         (abundant-nums (abundants 1 N))
         (sum 0))
    (do ((i 1 (+ i 1)))
        ((> i 28123) sum)
      (if (not (sum-of-two? abundant-nums i))
          (begin
            (set! sum (+ sum i))
            (display i)
            (newline))))
    (display "solution: ")
    (display sum)
    (newline)))

(main)
