(define (char->digit c)
  (if (char-numeric? c)
      (- (char->integer c) 48)
      #f))

(define (digit->char d)
  (if (and (>= d 0) (<= d 9))
      (integer->char (+ d 48))
      #f))

(define (strnum->vecnum strnum)
  ;; (strnum->vecnum "1234")
  ;; => #(4 3 2 1)
  (list->vector (reverse (map char->digit (string->list strnum)))))

(define (vecnum-add vecnum1 vecnum2)
  ;; (vecnum->strnum (vecnum-add (strnum->vecnum "268") (strnum->vecnum "37")))
  ;; => "305"
  (let* ((len1 (vector-length vecnum1))
         (len2 (vector-length vecnum2))
         (len (+ (max len1 len2) 1))
         (vecnumres (make-vector len)))
    (do ((i 0 (+ i 1))
         (carry 0))
        ((= (- len 1) i) vecnumres)
      (let* ((sum (+ (if (< i len1) (vector-ref vecnum1 i) 0)
                     (if (< i len2) (vector-ref vecnum2 i) 0)
                     carry))
             (digit (if (>= sum 10) (- sum 10) sum)))
        (set! carry (if (>= sum 10) 1 0))
        (vector-set! vecnumres i digit)
        (vector-set! vecnumres (+ i 1) carry)))
    (if (= (vector-ref vecnumres (- (vector-length vecnumres) 1)) 0)
        (list->vector (reverse (cdr (reverse (vector->list vecnumres)))))
        vecnumres)))

(define (main)
  (call-with-current-continuation
   (lambda (exit)
     (let loop ((i 1)
                (num1 (strnum->vecnum "0"))
                (num2 (strnum->vecnum "1")))
       (if (<= i 1000000)
           (let* ((fib num2))
             (if (= (vector-length fib) 1000)
                 (begin (display i)
                        (newline)
                        (exit)))
             (loop (+ i 1)
                   num2
                   (vecnum-add num1 num2))))))))

;; answer: 4782
(main)
