(define (digits x)
  (let loop ((x (abs x))
             (lst '()))
    (if (= x 0)
        lst
        (loop (quotient x 10) (cons (remainder x 10) lst)))))

(define (solve)
  (do ((i 1 (+ i 1))
       (digit-sum 1)
       (mul 1))
      ((> i 1000000) mul)
    (let loop ((digs (digits i)))
      (if (not (null? digs))
          (begin
            (let ((d (car digs)))
              (if (or (= digit-sum 1)
                      (= digit-sum 10)
                      (= digit-sum 100)
                      (= digit-sum 1000)
                      (= digit-sum 10000)
                      (= digit-sum 100000)
                      (= digit-sum 1000000))
                  (begin
                    (display digit-sum)
                    (display ": ")
                    (display d)
                    (newline)
                    (set! mul (* mul d))))
              (set! digit-sum (+ digit-sum 1))
              (loop (cdr digs))))))))

(define (main)
  (let ((res (solve)))
    (display "solution: ")
    (display res)
    (newline)))

(main)
