(define (digits->num lst)
  (let loop ((mul 1)
             (lst (reverse lst))
             (acc 0))
    (if (null? lst)
        acc
        (loop (* mul 10) (cdr lst) (+ acc (* (car lst) mul))))))

(define (vector-swap! vec i j)
  (let ((vali (vector-ref vec i)))
    (vector-set! vec i (vector-ref vec j))
    (vector-set! vec j vali)
    vec))

(define (permutations vec)
  ;; Heap's algorithm (https://en.wikipedia.org/wiki/Heap%27s_algorithm)
  (let ((perms (list)))
    (let loop ((k (vector-length vec))
               (vec vec))
      (if (= k 1)
          (set! perms (cons (vector-copy vec) perms))
          (begin
            (loop (- k 1) vec)
            (do ((i 0 (+ i 1)))
                ((= i (- k 1)) vec)
              (vector-swap! vec
                            (if (= (modulo k 2) 0) i 0)
                            (- k 1))
              (loop (- k 1) vec)))))
    (reverse perms)))

(define-syntax do-permutations
  (syntax-rules ()
    ((_ (vec value) body ...)
     (let ((vec value))
       (let loop ((k (vector-length vec))
                  (vec vec))
         (if (= k 1)
             (begin body ...)
             (begin
               (loop (- k 1) vec)
               (do ((i 0 (+ i 1)))
                   ((= i (- k 1)) vec)
                 (vector-swap! vec
                               (if (= (modulo k 2) 0) i 0)
                               (- k 1))
                 (loop (- k 1) vec)))))))))

(define (solve)
  (let ((digits (vector 0 1 2 3 4 5 6 7 8 9))
        (sum 0))
    (do-permutations (vec digits)
                     (if (and (= (modulo (digits->num (list (vector-ref vec 1)
                                                            (vector-ref vec 2)
                                                            (vector-ref vec 3)))
                                         2)
                                 0)
                              (= (modulo (digits->num (list (vector-ref vec 2)
                                                            (vector-ref vec 3)
                                                            (vector-ref vec 4)))
                                         3)
                                 0)
                              (= (modulo (digits->num (list (vector-ref vec 3)
                                                            (vector-ref vec 4)
                                                            (vector-ref vec 5)))
                                         5)
                                 0)
                              (= (modulo (digits->num (list (vector-ref vec 4)
                                                            (vector-ref vec 5)
                                                            (vector-ref vec 6)))
                                         7)
                                 0)
                              (= (modulo (digits->num (list (vector-ref vec 5)
                                                            (vector-ref vec 6)
                                                            (vector-ref vec 7)))
                                         11)
                                 0)
                              (= (modulo (digits->num (list (vector-ref vec 6)
                                                            (vector-ref vec 7)
                                                            (vector-ref vec 8)))
                                         13)
                                 0)
                              (= (modulo (digits->num (list (vector-ref vec 7)
                                                            (vector-ref vec 8)
                                                            (vector-ref vec 9)))
                                         17)
                                 0)
                              )
                         (let ((num (digits->num (vector->list vec))))
                           (set! sum (+ sum num))
                           (display num)
                           (newline))))
    (display "sum: ")
    (display sum)
    (newline)))

(solve)
